[book]
authors = ["k4yt3x"]
language = "en"
multilingual = false
title = "Video2X Documentations"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/k4yt3x/video2x"
edit-url-template = "https://github.com/k4yt3x/video2x/edit/master/docs/book/{path}"
